// Generated by https://quicktype.io

import { Inventory } from "./inventory";

export interface IProduct {
  _id?: string;
  category: string;
  _createdAt: string;
  name?: string;
  brand: {
    // [key: string]: string | number;
    _id?: string;
    logo?: string;
    name: string;
  };
  spus?: [];
  skus?: Sku[];
  spu: {
    imageURLs?: ImageURL[];
    _id?: string;
    name?: string;
    skus?: Sku[];
    link?: string;
  };
  imageURLs: ImageURL[];
  images?: ImageURL[];
  // skus: Sku[];
  _updatedAt: string;
  price: number;
  // inventories: {
  //   _id: string;
  //   _ref: string;
  //   spu: {
  //     _ref: string;
  //   };
  //   skus: {
  //     _id: string;
  //     id?: string;
  //     sku: { _ref: string; _type: string };
  //     _key: string;
  //     _type: string;
  //   }[];
  // }[];
}

type images = string[];
export interface ImageURL {
  _id?: string;
  asset: Asset;
}

interface Asset {
  _id: string;
  _ref: string;
  url: string;
}

export interface Sku {
  price?: number;
  remainQuantity?: number;
  _id?: string;
  _ref?: null;
  attribute: Attribute;
  spu?: IProduct["spu"] & { spuId: string };
  inventory?: Inventory;
  // inventory:
  // quantity?: number;
}

export interface SPU {
  imageURLs?: ImageURL[];
  _id?: string;
  name?: string;
  skus?: Sku[];
  link?: string;
}

interface Attribute {
  color: string;
  size: string;
}
