// Generated by https://quicktype.io

export interface IProduct {
  _id: string;
  category: string;
  _createdAt: string;
  name: string;
  brand: string;
  link: string;
  imageURLs: ImageURL[];
  skus: Skus[];
  _updatedAt: string;
}

interface ImageURL {
  asset: Asset;
}

interface Asset {
  url: string;
}

interface Skus {
  price: number;
  remainQuantity: number;
  _id: string;
  _ref: null;
  attribute: Attribute;
}

interface Attribute {
  color: string;
  size: string;
}
