// Generated by https://quicktype.io

export interface IProduct {
  _id: string;
  category: string;
  _createdAt: string;
  name: string;
  brand: string;
  link: string;
  imageURLs: ImageURL[];
  skus: Sku[];
  _updatedAt: string;
  price: number;
}

interface ImageURL {
  _id?: string;
  asset: Asset;
}

interface Asset {
  _id: string;
  _ref: string;
  url: string;
}

export interface Sku {
  price?: number;
  remainQuantity?: number;
  _id?: string;
  _ref?: null;
  attribute: Attribute;
}

interface Attribute {
  color: string;
  size: string;
}
