import * as React from "react";
import type { Metadata } from "next";

import "../styles/globals.css";
import SideNav from "~components/Layout/SideNav";
import Avatar from "~components/Layout/Avatar";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { NextAuthProvider } from "./providers/nextAuth";
import MainConainer from "~components/mainContainer";
import InjectProviders from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html>
      <body>
        <InjectProviders>
          <MainConainer>{children}</MainConainer>
        </InjectProviders>
      </body>
    </html>
  );
};

export default Layout;
