import axios from "axios";

const VITE_AUTH_REDIRECT_URI = import.meta.env.VITE_AUTH_REDIRECT_URI;
const VITE_AUTH_RESPONSE_TYPE = import.meta.env.VITE_AUTH_RESPONSE_TYPE;
const VITE_AUTH_CLIENT_ID = import.meta.env.VITE_AUTH_CLIENT_ID;
const VITE_AUTH_CLIENT_SECRET = import.meta.env.VITE_AUTH_CLIENT_SECRET;
const VITE_AUTH_SCOPE = import.meta.env.VITE_AUTH_SCOPE;
const VITE_AUTH_URL = import.meta.env.VITE_AUTH_URL;
export const Auth_URL = `${VITE_AUTH_URL}?redirect_uri=${VITE_AUTH_REDIRECT_URI}&response_type=${VITE_AUTH_RESPONSE_TYPE}&client_id=${VITE_AUTH_CLIENT_ID}&scope=${VITE_AUTH_SCOPE}`;
// Generated by https://quicktype.io

export interface IGoogleAuth {
  access_token: string;
  expires_in: number;
  scope: string;
  token_type: string;
}

export const signInWithGoogle = async ({
  code = "",
  grantType = "refresh_token",
}): Promise<IGoogleAuth> => {
  const codeORrefresh_token =
    grantType === "refresh_token"
      ? {
          refresh_token: code,
        }
      : {
          code,
        };

  const response = await axios.post<IGoogleAuth>(
    "https://oauth2.googleapis.com/token",
    {
      client_id: VITE_AUTH_CLIENT_ID,
      client_secret: VITE_AUTH_CLIENT_SECRET,
      grant_type: grantType,
      redirect_uri: VITE_AUTH_REDIRECT_URI,
      ...codeORrefresh_token,
    }
  );

  return response.data;
};
